### ISSUE TITLE
Line comment for pig should be --

### ISSUE THREAD

**Issue by swordfishray** [gandola/pig-vs-extension#4]
https://github.com/gandola/pig-vs-extension/blob/d0fe365e26082464fcf9ecaa5c9fef41f311e474/pig.configuration.json#L4

https://pig.apache.org/docs/r0.7.0/piglatin_ref1.html#Using+Comments+in+Scripts

Thanks!

**Comment by gandola** [comment]
Fixed!
I will update the plugin soon!

Thanks!
